services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

parameters:
    app.data_file_path: '%env(DATA_FILE_PATH)%'
    app.backup_enabled: '%env(bool:BACKUP_ENABLED)%'
    app.backup_interval: '%env(BACKUP_INTERVAL)%'